import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Layout from "@/components/Layout";
import profilePic from "../public/images/profile/developer-pic-1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons"
import Navbar from "@/components/Navbar";
import Main from "@/pages/Main";
import HireMe from "@/components/HireMe";
import Skills from "@/pages/Skills";
import Projects from "@/pages/Projects";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} font-mont bg-light w-full min-h`}>
      
    <body>{children}
    <Navbar/>
       <Main/>
       <HireMe/>
      
    
      
       
       <Skills/>
       <Projects/>
       <Footer/>

    
    </body>
  </html>
  );
}
